services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ./data:/data
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DJANGO_DB_PATH=/data/db.sqlite3
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=62.217.179.153,localhost,127.0.0.1,wedding-david-anastasia.ru
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend/public/videos:/app/public/videos
      - ./frontend/public/photos:/app/public/photos
    environment:
      - NEXT_PUBLIC_API_BASE=http://62.217.179.153
    depends_on:
      - backend
    expose:
      - "3000"

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./deploy/certbot/www:/var/www/certbot
      - ./deploy/certbot/conf:/etc/letsencrypt
