# Generated by Django 6.0.5 on 2026-05-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=200)),
                ('attendance', models.CharField(choices=[('yes', 'Приду'), ('no', 'Не смогу'), ('maybe', 'Пока не уверен(а)')], max_length=10)),
                ('day_1', models.BooleanField(default=False)),
                ('day_2', models.BooleanField(default=True)),
                ('day_3', models.BooleanField(default=False)),
                ('needs_transfer', models.BooleanField(default=False)),
                ('meal_choice', models.CharField(blank=True, choices=[('meat', 'Мясо'), ('fish', 'Рыба')], max_length=10)),
                ('allergies', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
